### ISSUE TITLE
🧊[Feature] Map editor

### ISSUE THREAD

**Issue by thebikwirm** [MrScautHD/Stellution#7]
Feature
=====

So some basic thing I was think for the map editor, not too sure how some of them will work but will put here anyway

TO-DO
=====

- [ ] terrain manipulation(raise, lower, level, plateau, etc)
- [ ] some form of object placement system(including precise movement and rotation of  in game objects, similar to unity editor)
- [ ] paint brushes for different textures such as rocks stone grass etc.
- [x] a few prefabs such as building and other objects that fit with the game
- [MAYBE] the ability to import custom prefabs with .obj files and some form of texture thing
- [ ] some custom prefabs such as thing like roads/ dirt paths etc
- [ ] checkpoints/spawn location

those are what I have thought of for now

Example
=====
![grafik](https://github.com/MrScautHD/Stellution/assets/65916181/4dfa4e55-2a5a-4eb4-a69d-7283025d42a0)

**Comment by TathanDev** [comment]
maybe the ability to add checkpoints, respawn points, ennemy spawn points etc...

**Comment by MrScautHD** [comment]
checkpoints?

**Comment by TathanDev** [comment]
I don't if it's gonna be an adventure map (If we die late in the level, we will not have to restart all). Otherwise, it's not necessary.

**Comment by MrScautHD** [comment]
it is no adventure map

**Comment by MrScautHD** [comment]
we need respawn points but no checkpoints

**Comment by MrScautHD** [comment]
jur for mini game maps
